config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :contacts
  #get 'home/index'
  get 'home/about'
  root 'home#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/contact.rb
class Contact < ApplicationRecord
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_many :contacts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :set_contact, only: %i[ show edit update destroy ]
  before_action :correct_user, only: [:edit, :update, :destroy]
  # GET /contacts or /contacts.json
  def index
    @contacts = Contact.all
  end

  # GET /contacts/1 or /contacts/1.json
  def show
  end

  # GET /contacts/new
  def new
    #@contact = Contact.new
    @contact = current_user.contacts.build
  end

  # GET /contacts/1/edit
  def edit
  end

  # POST /contacts or /contacts.json
  def create
    #@contact = Contact.new(contact_params)
    @contact = current_user.contacts.build(contact_params)

    respond_to do |format|
      if @contact.save
        format.html { redirect_to contact_url(@contact), notice: "Contact was successfully created." }
        format.json { render :show, status: :created, location: @contact }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contacts/1 or /contacts/1.json
  def update
    respond_to do |format|
      if @contact.update(contact_params)
        format.html { redirect_to contact_url(@contact), notice: "Contact was successfully updated." }
        format.json { render :show, status: :ok, location: @contact }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contacts/1 or /contacts/1.json
  def destroy
    @contact.destroy

    respond_to do |format|
      format.html { redirect_to contacts_url, notice: "Contact was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def correct_user
    @contact = current_user.contacts.find_by(id: params[:id])
    redirect_to contacts_path, notice: "Not Authorized" if @contact.nil?
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contact
      @contact = Contact.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def contact_params
      params.require(:contact).permit(:first_name, :last_name, :email, :phone, :user_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/contacts/_contact.html.erb
<div id="<%= dom_id contact %>">
  <p>
    <strong>First name:</strong>
    <%= contact.first_name %>
  </p>

  <p>
    <strong>Last name:</strong>
    <%= contact.last_name %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= contact.email %>
  </p>

  <p>
    <strong>Phone:</strong>
    <%= contact.phone %>
  </p>

</div>

app/views/contacts/_form.html.erb
<%= form_with(model: contact) do |form| %>
  <% if contact.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(contact.errors.count, "error") %> prohibited this contact from being saved:</h2>

      <ul>
        <% contact.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :first_name, style: "display: block" %>
    <%= form.text_field :first_name %>
  </div>

  <div>
    <%= form.label :last_name, style: "display: block" %>
    <%= form.text_field :last_name %>
  </div>

  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email %>
  </div>

  <div>
    <%= form.label :phone, style: "display: block" %>
    <%= form.text_field :phone %>
  </div>

  <div>
    <!--<%= form.label :user_id, style: "display: block" %>-->
    <%= form.text_field :user_id, id: :contact_user_id, value: current_user.id, type: :hidden %>
  </div>
  <br/>
  

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/contacts/edit.html.erb
<h1>Editing contact</h1>

<%= render "form", contact: @contact %>

<br>

<div>
  <%= link_to "Show this contact", @contact %> |
  <%= link_to "Back to contacts", contacts_path %>
</div>

app/views/contacts/index.html.erb
<h1>Contacts</h1>
<head>
    
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    </head>

<div id="contacts" class="row">

 <% @contacts.each do |contact| %>
    <% if contact.user == current_user %>
      <div class="col-sm-4"><br/>
        <div class="card" style="width: 20rem;">
          <div class="card-body">
            <%= render contact %>
            <p>
              <%= link_to "Show this contact", contact %>
            </p>
          </div>
        </div>
      </div>
    <% end %>
  <% end %>

</div>
<br/><br/>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>
<%= link_to "New contact", new_contact_path, class:"btn btn-primary" %>

app/views/contacts/new.html.erb
<h1>Add new contact</h1>

<%= render "form", contact: @contact %>

<br>

<div>
  <%= link_to "Back to contacts", contacts_path %>
</div>

app/views/contacts/show.html.erb
<%= render @contact %>

<div>
  <%= link_to "Edit this contact", edit_contact_path(@contact) %> |
  <%= link_to "Back to contacts", contacts_path %>
  
  <%= button_to "Delete this contact", @contact, method: :delete %>
</div>

app/views/home/_header.html.erb
<!--<nav class="navbar navbar-expand-lg bg-dark">-->
<nav class="navbar border-bottom border-dark navbar-expand-lg" style="background-color: #e0bbe4">
  <div class="container-fluid">
    <%= link_to 'Phone Book', root_path, class:"navbar-brand" %>
    <!--<a class="navbar-brand" href="#">Phone Book</a>-->
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <!--<li class="nav-item">
            <%= link_to 'About Me', home_about_path, class:"nav-link"%>
          <a class="nav-link" href="#">Link</a>-->
        </li>  
        
       
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to 'Contacts', contacts_path, class:"nav-link"%>
            <!--<a class="nav-link" href="#">Link</a>-->
          </li>
            <li class="nav-item">
            <%= link_to 'Add Contact', new_contact_path, class:"nav-link"%>
            <!--<a class="nav-link" href="#">Link</a>-->
          </li>
          <li class="nav-item">
            <%= link_to 'Edit Profile', edit_user_registration_path, class:"nav-link"%>
            <!--<a class="nav-link" href="#">Link</a>-->
          </li>
          <li class="nav-item">
            <%= button_to 'Sign Out', destroy_user_session_path, method: :delete, class:"nav-link" %>
            <!--<a class="nav-link" href="#">Link</a>-->
          </li>
        
        <% else %>
          <li class="nav-item">
              <%= link_to 'Sign Up', new_user_registration_path, class:"nav-link"%>
            <!--<a class="nav-link" href="#">Link</a>-->
          </li>
          <li class="nav-item">
              <%= link_to 'Sign In', new_user_session_path, class:"nav-link"%>
            <!--<a class="nav-link" href="#">Link</a>-->
          </li>
        <% end %>
      </ul>
      <!--<form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-primary" type="submit">Search</button>
      </form>-->
    </div>
  </div>
</nav>

app/views/home/about.html.erb
<h1>About suss</h1>
This is going good

app/views/home/index.html.erb
<h1> Hello </h1>
<% if user_signed_in? %>
    <h1><%= current_user.email %></h1>    
<% end %>

app/views/layouts/_alerts.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <%= notice %>
  <button type="button" class="close fade" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <title>PhoneBook</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Bootstrap demo</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>
  <body>
    <%= render 'home/header' %>
    <div class="container">
    <br/>
    <% if notice %>
      <%= render 'layouts/alerts' %>
    <% end %>
      <%= yield %>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>
  </body>
</html>